# Generated by Django 3.0.2 on 2020-01-24 10:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('picture', models.ImageField(upload_to='inage/')),
                ('textarea', ckeditor.fields.RichTextField()),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
