# Generated by Django 3.0.2 on 2020-05-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='published_date',
            new_name='publishedDate',
        ),
    ]
